name: protech_mobile_chat_stream
description: "A new Flutter project."
publish_to: "none"
version: 0.1.7

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  bloc: ^8.1.4
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_slidable: ^3.1.1
  get_it: ^8.0.0
  grouped_list: ^6.0.0
  
  path_provider: ^2.1.4
  easy_localization: ^3.0.7
  syncfusion_flutter_barcodes: ^26.2.8
  image_picker: ^1.1.2
  webview_flutter: ^4.8.0
  # mobile_scanner: ^5.1.1
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  uuid: ^4.5.1
  loader_overlay: ^4.0.2
  file_picker: ^8.1.7
  open_file: ^3.5.4
  chewie: ^1.8.5
  video_player: ^2.9.1
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  get_storage: ^2.1.1
  flutter_svg: ^2.0.10+1
  emoji_picker_flutter: ^3.1.0
  any_link_preview: ^3.0.2
  flutter_styled_toast: ^2.2.1
  stream_video: ^0.5.3

  stream_video_flutter: ^0.5.3
  stream_video_push_notification: ^0.5.3
  stream_video_screen_sharing: ^0.5.4
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  flutter_callkit_incoming: ^2.0.4+2
  shared_preferences: ^2.3.2
  audio_waveforms: ^1.0.5
  smooth_page_indicator: ^1.2.0+3
  flutter_secure_storage: ^9.2.2
  giphy_picker: ^3.0.2
  stomp_dart_client: ^2.1.0
  mobile_scanner: ^6.0.2
  path: ^1.9.0
  lottie: ^3.1.3
  country_code_picker: ^3.1.0
  fixnum: ^1.1.1
  turms_client_dart: 
    path: /Users/jerry/Documents/development/turms-nov-2024-mobile/turms-client-dart
  flutter_image_compress: ^2.3.0
  no_screenshot: ^0.3.1
  flutter_local_notifications: ^18.0.1
  internet_connection_checker_plus: ^2.7.0
  flutter_launcher_icons: ^0.14.2
  widgets_to_image: ^1.0.0
  gal: ^2.3.1
  sticky_grouped_list: ^3.1.0
  record: ^5.2.0
  better_player_plus: ^1.0.8
  get_video_thumbnail: ^0.7.0
  sqlite3_flutter_libs: ^0.5.29
  volume_controller: ^2.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.21.0
  build_runner: ^2.4.11

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Buttons/
    - assets/reaction/
    - assets/icons/
    - assets/translations/
    - assets/default-img/
    - assets/lottie/
    - assets/tnc/
    - lib/.env
