// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrRYYdAPUjP6DAoiLT3mm5KnZYXGbq2LI',
    appId: '1:828623641598:web:5b46b939be15782c82beaf',
    messagingSenderId: '828623641598',
    projectId: 'protech-chat',
    authDomain: 'protech-chat.firebaseapp.com',
    storageBucket: 'protech-chat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC131tUdNkt2ZVIVzinZMzGtFZXeAwlDNo',
    appId: '1:828623641598:android:95a2a1b33378125482beaf',
    messagingSenderId: '828623641598',
    projectId: 'protech-chat',
    storageBucket: 'protech-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyAUv1ZcM0m10xttQ4vmSWdfIds4SRCEA',
    appId: '1:828623641598:ios:ff8d85ae9c7156aa82beaf',
    messagingSenderId: '828623641598',
    projectId: 'protech-chat',
    storageBucket: 'protech-chat.firebasestorage.app',
    iosBundleId: 'my.com.prochat.prochat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyAUv1ZcM0m10xttQ4vmSWdfIds4SRCEA',
    appId: '1:828623641598:ios:a2366d51f9bca1ff82beaf',
    messagingSenderId: '828623641598',
    projectId: 'protech-chat',
    storageBucket: 'protech-chat.firebasestorage.app',
    iosBundleId: 'com.example.protechMobileChatStream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNuh4jYB17wyaHF94OE1pr9SyfuQNggnw',
    appId: '1:828623641598:web:0edbde587898865b82beaf',
    messagingSenderId: '828623641598',
    projectId: 'protech-chat',
    authDomain: 'protech-chat.firebaseapp.com',
    storageBucket: 'protech-chat.firebasestorage.app',
  );

}